---
mark/lightbox: 'http://mark.reevoo.com/reevoomark/en-GB/product?sku=SONDSCW300&retailer=JSP&badge_style=imagescoresonly_sny104x82'
reevoo.com/home_page: 'http://www.reevoo.com'
reevoo.com/category_page: 'http://www.reevoo.com/browse/product_type/televisions'
reevoo.com/product_page/details_tab: 'http://www.reevoo.com/p/nintendo-wii#/product-features'
reevoo.com/product_page/offers_tab: 'http://www.reevoo.com/p/nintendo-wii#/offers'
reevoo.com/product_page/related_products_tab: 'http://www.reevoo.com/p/nintendo-wii#/alternatives'
reevoo.com/product_page/reviews_tab: 'http://www.reevoo.com/p/nintendo-wii#/reviews'
reevoo.com/product_page/expert_reviews_tab: 'http://www.reevoo.com/p/nintendo-wii#/expert-reviews'
jfbi/home_page: 'http://www.justbuythisone.com/'
jfbi/product_page: 'http://www.justbuythisone.com/best-tv'
